#!/usr/bin/env python3
"""Write 3ds/sources.mk: the game and libultra sources Makefile.pc lists."""
import re

BS = chr(92)
mk = open("Makefile.pc", encoding="utf-8").read()


def source_list(name):
    lines = mk.split("\n")
    start = next(i for i, l in enumerate(lines) if l.startswith(name + " :="))
    out = []
    for line in lines[start + 1:]:
        item = line.strip().rstrip(BS).strip()
        if item:
            out.append(item)
        if not line.rstrip().endswith(BS):
            break
    return out


game = [f for f in source_list("SRC_FILES") if not f.startswith("linux/")]
libultra = source_list("LIBULTRA_FILES")
with open("3ds/sources.mk", "w", encoding="utf-8", newline="\n") as f:
    f.write("# Generated by 3ds/gen_sources.py from Makefile.pc.\n")
    for name, files in (("GAME_FILES", game), ("LIBULTRA_FILES", libultra)):
        f.write(name + " := " + BS + "\n")
        for item in files:
            f.write("\t" + item + " " + BS + "\n")
        f.write("\n")
print(len(game), "game files,", len(libultra), "libultra files")
